<a href="https://colab.research.google.com/github/JulianEduardoMendez/programacion1/blob/main/EscrituraArchivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
with open("archivo.txt", "w") as f:
  f.write("Hola, este es un archivo de texto.\n")
  f.write("Segunda linea.")

In [4]:
with open("archivo.txt", "r") as f:
  print(f.read())

Hola, este es un archivo de texto.
Segunda linea.

In [5]:
from google.colab import files
files.download("archivo.txt")

In [6]:
with open("archivo.txt", "a") as f:
  f.write("\nEsta es una nueva línea añadida.")

In [7]:
with open("archivo.txt", "r") as f:
  print(f.read())

Hola, este es un archivo de texto.
Segunda linea.
Esta es una nueva línea añadida.

In [8]:
with open("ejemplo.txt", "w") as f:
  f.write("Este es un ejemplo \nHola")

In [9]:
with open("ejemplo.txt", "r") as f:
  print(f.read())

Este es un ejemplo
Hola

In [10]:
from google.colab import files
uploaded = files.upload()

Saving archivo.txt to archivo (1).txt

In [11]:
with open("archivo (1).txt", "r") as f:
  print(f.read())

Hola, este es un archivo de texto.
Segunda linea.

In [17]:
with open("platillo.txt", "w") as f:
  f.write("Este archivo fue completamente modificado\n")
  f.write("Nueva línea\n")
  f.write("Nueva línea2\n")

In [18]:
with open("platillo.txt", "r") as f:
  print(f.read())

Este archivo fue completamente modificado
Nueva línea
Nueva línea2

In [19]:
from google.colab import files
files.download("platillo.txt")

CSV

In [21]:
import csv
datos = [["Nombre", "Edad", "Ciudad"], ["Ana", 25, "Bogotá"], ["Luis", 30, "Medelín"], ["Carlos", 28, "Cali"]]
with open("datos.csv", "w", newline="") as f:
  writer = csv.writer(f)
  writer.writerows(datos)

In [22]:
with open("datos.csv", "r") as f:
  print(f.read())

Nombre,Edad,Ciudad
Ana,25,Bogotá
Luis,30,Medelín
Carlos,28,Cali

In [23]:
files.download("datos.csv")

In [24]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [25]:
ruta = "/content/drive/MyDrive/datos.csv"
import shutil as st
st.copy("datos.csv", ruta)

'/content/drive/MyDrive/datos.csv'

In [26]:
with open(ruta, "r") as f:
  print(f.read())

Nombre,Edad,Ciudad
Ana,25,Bogotá
Luis,30,Medelín
Carlos,28,Cali

In [27]:
with open(ruta, "r") as f:
  data = list(csv.reader(f))

data.append(["Diego", "28", "Armenia"])
data

[['Nombre', 'Edad', 'Ciudad'],
 ['Ana', '25', 'Bogotá'],
 ['Luis', '30', 'Medelín'],
 ['Carlos', '28', 'Cali'],
 ['Diego', '28', 'Armenia']]

In [28]:
import pandas as pd
data1 = pd.DataFrame(data)
data1

        0     1        2
0  Nombre  Edad   Ciudad
1     Ana    25   Bogotá
2    Luis    30  Medelín
3  Carlos    28     Cali
4   Diego    28  Armenia

In [29]:
import csv

ruta = "/content/drive/MyDrive/datos.csv"

# Leer
with open(ruta, "r") as f:
    data = list(csv.reader(f))

# Mostrar antes
print("ANTES:")
print(data)

# Agregar fila
data.append(["Diego", "28", "Armenia"])

# Guardar
with open(ruta, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)

# Mostrar después
print("\nDESPUÉS:")
with open(ruta, "r") as f:
    print(f.read())

ANTES:
[['Nombre', 'Edad', 'Ciudad'], ['Ana', '25', 'Bogotá'], ['Luis', '30', 'Medelín'], ['Carlos', '28', 'Cali']]

DESPUÉS:
Nombre,Edad,Ciudad
Ana,25,Bogotá
Luis,30,Medelín
Carlos,28,Cali
Diego,28,Armenia

In [30]:
import os
os.listdir("/content/drive/MyDrive")

['Colab Notebooks',
 'EVIDENCE CLASS 1 (2).pdf',
 'EVIDENCE CLASS 1 (1).pdf',
 'EVIDENCE CLASS 1.pdf',
 'Classroom',
 'MY ACTIVITY (2).docx',
 'MY ACTIVITY (1).docx',
 'MY ACTIVITY.docx',
 'atg-discuss-will (1).gdoc',
 'PROYECT PART 1 PRETENAGEARS 10 (1).docx',
 'LISTENING EXERCISE.docx',
 'MY EVIDENCE  xd.docx',
 'PROYECT PART 1 PRETENAGEARS 10.docx',
 'Doc2Myactivity qwq.docx',
 'top006-describing-people.gdoc',
 'lota Hurricane.gslides',
 'DOC-20221007-WA0014. (1).pdf',
 'DOC-20221007-WA0014..pdf',
 'factorización caso 3 y 4.pdf',
 'Untitled folder',
 'Trabajo, matemáticas videos',
 'INFORMATICA 11-1',
 'Sena video',
 'PORTAFOLIO JULIAN MENDEZ',
 'SAMUEL CUEVAS RAMIREZ.pdf',
 'Formulario sin título (3).gform',
 'Evaluación de matemáticas 11-1.gform',
 'Pedraza2823_343434.docx',
 '5 carta carnet.docx',
 'Formulario sin título (2).gform',
 'Formulario sin título (1).gform',
 'Formulario sin título.gform',
 'Saber leer_INSTITUTO CERVANTES.gdoc',
 'datos.csv']

In [31]:
import pandas as pd
df = pd.read_csv(ruta)
df

   Nombre  Edad   Ciudad
0     Ana    25   Bogotá
1    Luis    30  Medelín
2  Carlos    28     Cali
3   Diego    28  Armenia

In [32]:
df["Nueva_Columna"] = "valor"
df["Nueva_Columna"] = [10, 20, 30, None]
df

   Nombre  Edad   Ciudad  Nueva_Columna
0     Ana    25   Bogotá           10.0
1    Luis    30  Medelín           20.0
2  Carlos    28     Cali           30.0
3   Diego    28  Armenia            NaN